[package]
name = "accurate-time"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "*"
clap = { version = "*", features = ["derive"] }
fork = "*"
num_cpus = "*"
